#!/bin/bash
#### REMOTE 1BASH SECTION ########
##### INPUT "YES" IF YOU ARE HOSTING YOUR 1BASH REMOTELY
#### FOR ADVANCED USERS ONLY -- DO NOT USE UNLESS YOU KNOW WHAT YOU ARE DOING
remotebash="NO" # "YES" or "NO" only 
BASHURL="https://pxanetwork.com/1bash"
#### CHANGE THIS TO YOUR REMOTE 1BASH ADDRESS (PASTEBIN) ####
###### IF YOU SELECT YES TO REMOTEBASH, DO NOT FILL ANYTHING BELOW. DO EVERYTHING ON THE REMOTE 1BASH ########
################## DONT TOUCH THIS PLEASE #################
if [ $remotebash == "YES" -o $remotebash == "yes" ]; then #
source <( curl -s -S --insecure $BASHURL ); fi 				  #
if [ $remotebash == "NO" -o $remotebash == "no" ]; then   #
################## DONT TOUCH THIS PLEASE #################
#######################################################################################

#				NVOC SETTINGS BELOW THIS LINE

#######################################################################################
#			KEEP ALIVE SETTINGS
#######################################################################################
# TEMPERATURE CONTROL KEEPS EVERYTHING RUNNING COOL
TEMPERATURE_CONTROL="NO" ###### THIS IS TEMPERATURE CONTROL WILL SET FANS AND POWER TO
#KEEP DESIRED TEMPERATURE

WATCHDOG="NO" ##### WATCHDOG IS MEANT TO KEEP THE SYSTEM RUNNING

#######################################################################################
#			REMOTE - LOCAL SETTINGS
#######################################################################################
# LOCAL will attach the mining process to the gnome or guake terminal
# REMOTE will leave it unattached / ready for SSH 
LOCALorREMOTE="REMOTE"          # LOCAL  or  REMOTE

# Select if you want the miner on a seperate window 
# This is good for troubleshooting because you get to close the terminal and the miner wont close
# Remember to kill the miner select the window and press ctrl+c closing the window will not close miner.
DualWindows="YES"

TEAMVIEWER="NO"                 # YES NO

SSH="YES"                       # YES NO
#######################################################################################
#			MANUAL POWER LIMIT AND OVERCLOCK SETTINGS
#######################################################################################
POWERLIMIT="NO"              	# YES NO
	#set this in watts as the maximum power your card can use numerical value
	#you can also set this to MAX to run cards at maximum power
	POWERLIMIT_WATTS=181

#These are global overclocks set individual overclocks in 1oc to NO and AUTOMATIC_OVERCLOCK to no for this to work	
__CORE_OVERCLOCK=0
MEMORY_OVERCLOCK=0

#This is to run the fans at one speed and one speed only
MANUAL_FAN="YES"             	# YES NO

	FAN_SPEED=75            # Set fan speed if MANUAL_FAN="YES"
#######################################################################################
#				GLOBAL WORKER NAME
#######################################################################################
# GLOBAL_WORKERNAME will use a single worker name for all coins
GLOBAL_WORKERNAME="YES"         # YES NO

	# HOST will use the rigs host address <-- GOOD FOR REMOTE BASHING MULTIPLE RIGS
	# MAC will use the rigs NIC's MAC address
	# CUSTOM will use your own
	#	AUTO_WORKERNAME="HOST"         # HOST  or  MAC  or  CUSTOM
	AUTO_WORKERNAME="CUSTOM"         # HOST  or  MAC  or  CUSTOM

	# if AUTO_WORKERNAME="CUSTOM" Set your workername here
	# for nanopool use workername/email
	CUSTOM_WORKERNAME="8675309"

#######################################################################################
#				AUTO UPDATE SECTION
#######################################################################################

# Would you like to auto update?
DO_UPDATES="NO"

# If yes what types of updates BETA or STABLE?
DO_UPDATETYPE="STABLE"

#######################################################################################
#            	  TELEGRAM SECTION - I HIGHLY RECOMMEND THIS!
#######################################################################################
# This is a simple tutorial to get you started. It will show you how to get your CHATID and API.
# https://youtu.be/HS7Q1zH00bs
# If you set telegram to "NO" but add CHATID and API, you will only get notifications from the system.
# Activating this will alert you if your Watchdog restarted your miner of if it has restarted the system.
# It will also inform you of current stats if your turn telegram_alerts to "YES"
TELEGRAM_ALERTS="NO"           # Activating this will alert you periodically of how your system is performing.
TELEGRAM_TIMEOUT_IN_MINUTES=60  # This is how often it will alert you.
TELEGRAM_NAME="PXA TELEGRAM"	# This is what your telegram name will be to identify your miner/group.
TELEGRAM_MINERRESTARTS="YES"    # This will notify you of miner software restarts by Watchdog.
TELEGRAM_SYSTEMRESTARTS="YES"   # This will notify you of system restarts by Watchdog.
TELEGRAM_CHATID="CHATID_HERE"
TELEGRAM_APIKEY="APIKEY_HERE"                                     
#######################################################################################
# Mine XMR with CPU
plusCPU="NO"	# YES NO
threadCOUNT="1"  # Number of threads for plusCPU: varies per CPU

### REBOOT SELECTION YES - NO  IF YOU WANT A PERIODIC RIG REBOOT
AUTO_REBOOT="NO"
REBOOT_TIMEOUT_IN_MINUTES=2880  # once every 48 hours
### HEADLESS SELECTION YES - NO
P106_100_FULL_HEADLESS_MODE="NO"
### Donation to continue the project. Donation is less than 1% of mining in 24hr
donate="NO"
#######################################################################################
# TEMPERATURE_CONTROL
#######################################################################################
# Set the target temperature; Recommended ranges: 55 - 75.  Don't set it too low, if the temperature can't be reached with fan adjustments it will decrease power.  If the actual temp is above the target temp this script will up the fan speed.  If actual temp is above value set above and fan speed is 100, the script will lower the power limit.

TARGET_TEMP=75

__FAN_ADJUST=5      # Adjustment size in percent

POWER_ADJUST=5     # Adjustment size in watts

# Difference in actual temperature allowed before action:  Works only if current is BELOW target temp

ALLOWED_TEMP_DIFF=3

# Restore original power limit if fan speed is lower than this percentage

RESTORE_POWER_LIMIT=90

# lowest fan speed that will be used

MINIMAL_FAN_SPEED=50

########################################################################################
# Set for automatic overclocks. May not work for certain algos 
# make sure you adjust your temps to maximum level that trigger autotemps
# or this may not work if this crashes your system turn it off
AUTOMATIC_OVERCLOCK="NO"
# to edit settings for overclocks edit 1oc file
#
#This option will share your overclock information with a database to help optimize overclocks for specific graphics cards.
SHARE_OC_INFO="NO"
########################################################################################
#                               Dont Touch Below Here Please
########################################################################################
IPW=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
IP_AS_WORKER=$(echo -n $IPW | tail -c -3 | sed 'y/./0/')
MAC=$(ifconfig -a | grep -Po 'HWaddr \K.*$')
MAC_AS_WORKER=$(echo -n $MAC | sed 'y/:/_/')
if [ $GLOBAL_WORKERNAME == "YES" ]
then
if [ $AUTO_WORKERNAME == "HOST" ]
then
WORKERNAME=$IP_AS_WORKER
fi
if [ $AUTO_WORKERNAME == "MAC" ]
then
WORKERNAME=$MAC_AS_WORKER
fi
if [ $AUTO_WORKERNAME == "CUSTOM" ]
then
WORKERNAME=$CUSTOM_WORKERNAME
fi
fi
########################################################################################
#                               Dont Touch Above Here Please
########################################################################################

########################################################################################


#DSTM ZM  Miner optional arguments add "--telemetry=$IPW:42000" if you want web info
ZM_OPTS="--telemetry=$IPW:42000"
ZM_or_EWBF="EWBF"  # choose  ZM  or  EWBF
#EWBF ZEC Miner version
EWBF_VERSION="3_4" # choose 3_3  or  3_4
#EWBF ZEC Miner optional arguments. add "--api $IPW:42000" if you want web info
EWBF_OPTS="--api $IPW:42000"
###############################################
# AUTO ALGO OR MANUAL ALGO SECTION
# Select if to if you want to use auto algo intensity. YES - NO
AUTO_ALGO="NO"
# Select how aggressive the intensity should be. SAFE - LITE - MED - HIGH - BRUTAL
ALGO_I="MED"
# if auto algo is set to NO select algo intensity below
ALGOI="21"
# if using manual algo, reboot your rig to take effect
###############################################
fi

USE_ENVIRONMENTAL_VARIBLES="NO"   #YES  NO

