#!/bin/bash
source ~/1bash
source ~/Resources
3MAIN_SEQUENCE_1
TMINER=miner

miner_CheckMiner
pkill -e $TMINER

3main_clearLogsOnBoot

3main_exportDisplay

sudo cp '/usr/lib/x86_64-linux-gnu/libOpenCL.so.1' '/usr/local/cuda/lib64/libOpenCL.so.1'

3main_connectedMonitorCheck

display_logo

#3MainC ## calls pxa

3main_reportGPU

3main_useEnvironmentalVariablesCheck

3Main_Sequence_2

GPUS=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | tail -1) # subsequent methods depend on this
NVD=nvidia-settings # subsequent methods depend on this

3main_slowUSBKeyModeCheck

3main_defaultOverclockAndFanChecks_nonP106

3Main_Sequence_3

gpu_checkCard ## sets let GPUP[${i}]=$POWERMAX (180) among other things

##### 

gpu_SetManualFan
gpu_setTemp ## populates TARGET_TEMP[]
gpu_setClock ## populates MEMORY_OVERCLOCK[] and __CORE_OVERCLOCK[]
gpu_setPower ## populates POWER_LIMIT[]
gpu_SetCardPower ## sets the card power rates from POWER_LIMIT[]
3MAIN_CHECKOC ## actually set the mem and core offsets via smi
miner_fix2
source ~/miner_prototypes

####

if [ "$LOCALorREMOTE" == "LOCAL" ]
then
 bash '/home/m1/Miners/Miner_Starter'
fi

while [ "$Loopback" == "Looper" ]
do
 sleep 120
done
