#!/bin/bash
source ~/1bash
source ~/Resources
3MAIN_SEQUENCE_1
TMINER=miner

miner_CheckMiner
pkill -e $TMINER

3main_clearLogsOnBoot

3main_exportDisplay

sudo cp '/usr/lib/x86_64-linux-gnu/libOpenCL.so.1' '/usr/local/cuda/lib64/libOpenCL.so.1'

3main_connectedMonitorCheck

logo
echo ""
3MainC

3main_reportGPU

3main_useEnvironmentalVariablesCheck

3Main_Sequence_2

GPUS=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | tail -1) # subsequent methods depend on this
NVD=nvidia-settings # subsequent methods depend on this

3main_slowUSBKeyModeCheck

gpu_setClock

3main_defaultOverclockAndFanChecks_nonP106

3Main_Sequence_3
3Main_Coin_Sequence

if [ "$LOCALorREMOTE" == "LOCAL" ]
then
 bash '/home/m1/Miners/Miner_Starter'
fi

while [ "$Loopback" == "Looper" ]
do
 sleep 120
done
