#!/bin/bash

if [ "$MINER" == "alccminer" ]
then
 miner_start1
 HCD='/home/m1/Miners/alccminer/ccminer'
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "ccminer223" ]
then
 miner_start1
 HCD='/home/m1/Miners/ccminer223/ccminer'
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "ccminer" ]
then
 HCD='/home/m1/Miners/ccminer/ccminer'
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "ccminer-xevan" ]
then
 miner_start1
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" --cpu-priority 0 -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "vertminer" ]
then
 HCD='/home/m1/Miners/vertminer/ccminer'
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" --cpu-priority 0 -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "KTccminer-cryptonight" ]
then
 HCD='/home/m1/Miners/KTccminer-cryptonight/ccminer'
 screen -dmSL miner "$HCD" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "KXccminer-skunk" ]
then
 HCD='/home/m1/Miners/KXccminer-skunk/ccminer'
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "SPccminer" ]
then
 HCD='/home/m1/Miners/SPccminer/ccminer'
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "TPccminer" ]
then
 HCD='/home/m1/Miners/TPccminer/ccminer'
 screen -dmSL miner "$HCD" -a "$MINER_ALGO" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -i "$MINER_INTENSITY"
fi

if [ "$MINER" == "SGminer" ]
then
 HCD='/home/m1/Miners/pasc/sgminer'
 screen -dmSL miner "$HCD" -k "$MINER_ALGO" -o "$MINER_POOL":"$MINER_PORT" -u "$MINER_ADDRESS" -p "$MINER_PWD" -I "$MINER_INTENSITY" -w 64 -g2
fi

if [ "$MINER" == "zm" ]
then
 HCD='/home/m1/Miners/zec/zm/5_8/zm'
 screen -dmSL miner "$HCD" --server "$MINER_POOL" --user "$MINER_ADDRESS" --pass "$MINER_PWD" --port "$MINER_PORT" --time "$ZM_OPTS" ;
fi

if [ "$MINER" == "ewbf_3_4" ]
then
 HCD='/home/m1/Miners/zec/v3_4/ewbf'
 screen -dmSL miner "$HCD" --eexit 3 --fee 0 --pec --server "$MINER_POOL" --user "$MINER_ADDRESS" --pass "$MINER_PWD" --port "$MINER_PORT" "$EWBF_OPTS" ;
fi

if [ "$MINER" == "genoil" ]
then
 HCD='/home/m1/Miners/eth/Genoil-U/ethminer'
 screen -dmSL miner "$HCD" -SP 2 -S "$MINER_POOL":"$MINER_PORT" -O "$MINER_ADDRESS":"$MINER_PWD" -U
fi

if [ "$MINER" == "ethminer" ]
then
 HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'
 screen -dmSL miner "$HCD" -SP 2 -S "$MINER_POOL":"$MINER_PORT" -O "$MINER_ADDRESS":"$MINER_PWD" -U
fi

if [ "$MINER" == "claymore" ]
then
 HCD="/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64"
 screen -dmSL miner "$HCD" -epool "$MINER_POOL":"$MINER_PORT" -ewal "$MINER_ADDRESS" -epsw "$MINER_PWD" -esm 3 -allpools 1 -estale 0 -dbg -1 -mode 1
fi

if [ "$MINER" == "xmr-stak-nvidia" ]
then
 HCD='/home/m1/Miners/xmr/stakGPU/bin/xmr-stak-nvidia'

 GPUS_FOR_XMR=0
 echo "" > /home/m1/Miners/tmp_threads

 while [ "$GPUS_FOR_XMR" != "$GPUS" ]
 do

 cat <<EOF >>/home/m1/Miners/tmp_threads
 { "index" : "$GPUS_FOR_XMR",
    "threads" : 32, "blocks" : 18,
    "bfactor" : 8, "bsleep" :  10,
    "affine_to_cpu" : false,
  },
EOF
 GPUS_FOR_XMR=$("$GPUS_FOR_XMR"+1)
 done

 THREADS=$(cat /home/m1/Miners/tmp_threads)

 cat <<EOF >/home/m1/Miners/xmr/stakGPU/bin/config.txt

 "gpu_threads_conf" : [
  "$THREADS"
 ],

 "use_tls" : false,
 "tls_secure_algo" : true,
 "tls_fingerprint" : "",

 "pool_address" : "$MINER_POOL",
 "wallet_address" : "$MINER_ADDRESS",
 "pool_password" : "$MINER_PWD",

 "call_timeout" : 10,
 "retry_time" : 10,
 "giveup_limit" : 0,

 "verbose_level" : 4,

 "h_print_time" : 60,

 "output_file" : "",

 "httpd_port" : 0,

 "prefer_ipv4" : true
EOF

 'cd /home/m1/Miners/xmr/stakGPU/bin'

 screen -dmSL miner "$HCD"

 rm /home/m1/Miners/tmp_threads
fi
