#!/bin/bash
source ~/processes/3_main
source ~/processes/auto
source ~/processes/display
source ~/processes/gpu
source ~/processes/log
source ~/processes/miner
source ~/processes/telegram
source ~/processes/temp
source ~/1active
source ~/1oc
## Do not remove: Dynamically set pool and miner (if overriden) from 1active choice ##
source ~/pools/templates/"$POOL_CHOSEN"
if [ -n "$MINER_CHOSEN" ]
then 
 MINER="$MINER_CHOSEN"
fi
## Do not remove above ################
nvOC_VER="1.9.6"
BETA_VER="1.9.6"
OB_VER="1.9.4"
OC_VER="1.9.8"
OCC_VER="1.9.4"
TEMP_VER="1.9.8"
WDOG_VER="1.9.8"
sudo chown -R m1 /tmp/;sudo chown -R m1 /tmp;

gpu_setClock
gpu_setPower
gpu_setTemp
miner_CheckMiner

CURRENT_COIN=$COIN;

gpu_isNormalOr1050

gpu_setClock
gpu_setPower
gpu_setTemp

display_loadFormatting

display_checkMonitor

auto_setDefaults

gpu_checkCard

TELEGRAM_TYPE="papampi";

gpu_M_GPU

miner_setDefaults

tel_TELEGRAM

