#!/bin/bash
source ~/pools/MININGPOOLHUB.defaults

if [ -z $PASSWORD_OVERRIDE ]
then
 PASSWORD=$PASSWORD_OVERRIDE
fi

#######################################

MINER_PWD="$PASSWORD"

## Pool ports #########################

case $COIN in
 "ADZ")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20529";;
 "BSTY")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20543";;
 "BTG") 
     MINER_POOL="us-east.equihash-hub.miningpoolhub.com"
     MINER_PORT="20595";;
 "DASH")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20465";;
 "DGB")
     MINER_POOL="hub.miningpoolhub.com"
     if [ "$ALGO" == "myr-groestl" -o "$ALGO" == "myr-gr" ]
     then
      MINER_PORT="20499"
     elif [ "$ALGO" == "skein" ]
     then
      MINER_PORT="20527"
     fi
     ;;
 "ETN")
     MINER_POOL="us-east.cryptonight-hub.miningpoolhub.com"
     MINER_PORT="20596";;
 "ETC")
     MINER_POOL="us-east.ethash-hub.miningpoolhub.com"
     if [ $MINER == "qtminer" -o $MINER_CHOSEN == "qtminer" ]
     then
      MINER_PORT="20557"
     else
      MINER_PORT="20555"
     fi
     ;;
 "EXP")
     MINER_POOL="us-east.ethash-hub.miningpoolhub.com"
     if [ $MINER == "qtminer" -o $MINER_CHOSEN == "qtminer" ]
     then
      MINER_PORT="20567"
     else
      MINER_PORT="20565"
     fi
     ;;
 "FTC")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20510";;
 "GAME")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20576";;
 "GEO")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20524";;
 "GRS")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20486";;
 "LTC")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20460";;
 "MAX")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20461";;
 "MONA")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20593";;
 "MUSIC")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20585";;
 "SC")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20550";;
 "START")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20509";;
 "SXC")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20463";;
 "VTC")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20507";;
 "XMR")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20580";;
 "XMY")
     MINER_POOL="hub.miningpoolhub.com"
     if [ "$ALGO" == "myr-groestl" -o "$ALGO" == "myr-gr" ]
     then
      MINER_PORT="20479"
     elif [ "$ALGO" == "skein" ]
     then
      MINER_PORT="20528"
     elif [ "$ALGO" == "yescrypt" ]
     then
      MINER_PORT="20577"
     fi
     ;;
 "XVG")
     MINER_POOL="hub.miningpoolhub.com"
     MINER_PORT="20523";;
 "XZC")
     MINER_POOL="us-east.lyra2z-hub.miningpoolhub.com"
     MINER_PORT="20581";;
 "ZEC")
     MINER_POOL="us-east.equihash-hub.miningpoolhub.com"
     MINER_PORT="20570";;
 "ZEN")
     MINER_POOL="us-east.equihash-hub.miningpoolhub.com"
     MINER_PORT="20594";;
 "ZCL")
     MINER_POOL="us-east.equihash-hub.miningpoolhub.com"
     MINER_PORT="20575";;
esac

