#!/bin/bash
display_checkMonitor() {
 export GPU_FIRST_NVIDIA=`lspci | grep -E "VGA|3D controller" | head -n 1 | grep NVIDIA | wc -l`
 if [[ $GPU_FIRST_NVIDIA == 0 ]]; 
 then
  warnmsg=$(cat <<WARN
   ${BY}
##############################################################################
###									   ###
### You have connected monitor to integrated GPU on the motherboard?       ###
### Don't do this. Connect monitor to the 1st external GPU (in 16x slot).  ###
### However we will try to continue in 5 seconds.			   ###
###									   ###
##############################################################################
${N}
WARN
)
  rm -f /etc/X11/xorg.conf
  echo -e "$warnmsg"
  sleep 5
 fi
}

display_loadFormatting(){
 BB='\033[0;30m';
 DG='\033[1;30m';
 BR='\033[1;31m';
 BG='\033[1;32m';
 BY='\033[1;33m';
 BL='\033[0;34m';
 BBL='\033[1;34m';
 P='\033[0;35m';
 BP='\033[1;35m';
 BC='\033[1;36m';
 LG='\033[0;37m';
 W='\033[1;37m';
 N='\e[0m';
 B='\e[1m';
 R='\e[31m';
 G='\e[32m';
 C='\e[36m';
 Y='\e[33m';
};
