#!/bin/bash

Make_Logs_WDOG(){
 LOG1_FILE="/home/m1/Logs/5_wdog_log";
 echo -e "${B}${Y}Displaying the last 20 lines of Restart Logs${N}";
 tail -20 $LOG1_FILE;
 echo "";
 echo -e "${B}${Y}Displaying the last 20 lines of WatchDog Alert Logs${N}";
 ALERT1_LOG_FILE="/home/m1/Alerts/7_wdog_alertlog";
 tail -20 $ALERT1_LOG_FILE;
 if [ $TELEGRAM_TYPE != "papampi" -o $TELEGRAM_ALERTS == "NO" ];
 then 
  echo -e "${B}${Y}$(date)${N} - ${C}Starting WatchDog script.${N}"|tee -a ${LOG1_FILE};
 fi;
 if [[ $TELEGRAM_TYPE == "papampi"&&$TELEGRAM_ALERTS == "YES" ]];
 then 
  echo -e "${B}${Y}$(date)${N} - ${C}Starting WatchDog script.${N}"|tee -a ${LOG1_FILE};
 fi;
 echo "";
 for i in {16..21};
 do 
  echo -en "\e[42;4;${i}m ";
 done;
 echo -en "${B}WatchDog $WDOG_VER edited by PoisonXA - Activated${N}";
 for i in {21..16};
 do 
  echo -en "\e[42;4;${i}m \e[0m";
 done;
 echo "";
 echo "";
};

Make_Logs_Temp(){ 
 if [ $TEMPERATURE_CONTROL == "YES" ];
 then 
  echo "";
  for i in {16..21};
  do 
   echo -en "\e[42;4;${i}m ";
  done;
  echo -en "${B}TEMPERATURE CONTROL VERSION $TEMP_VER by MAXXIMUS and PoisonXA ARE TURNED ON${N}";
  for i in {21..16};
  do 
   echo -en "\e[42;4;${i}m \e[0m";
  done;
  echo "";
  echo "";
  sleep 1;
 fi;
 if [ $TEMPERATURE_CONTROL == "NO" ];
 then 
  echo "";
  for i in {16..21};
  do 
   echo -en "\e[41;4;${i}m ";
  done;
  echo -en "${B}TEMPERATURE CONTROL VERSION $TEMP_VER by MAXXIMUS and PoisonXA ARE TURNED OFF${N}";
  for i in {21..16};
  do 
   echo -en "\e[41;4;${i}m \e[0m";
  done;
  echo "";
  echo "";
  sleep 1;
 fi;
 LOG_FILE="/home/m1/Logs/6_autotemplog";
 echo -e "${B}${Y}Displaying the last 20 lines of Temp Logs${N}";
 tail -20 $LOG_FILE;
 OC_FILE="/home/m1/Logs/6_autooclog";
 OCC_FILE="/home/m1/Alerts/6_autooclastlog";
 echo -e "${B}${Y}Displaying the last 20 lines of Overclock Logs${N}";
 tail -20 $OC_FILE;
 echo -e "${B}${Y}Displaying the last 20 lines of Auto Temp Alert Logs${N}";
 ALERT_LOG_FILE="/home/m1/Alerts/6_temp_alertlog";
 tail -20 $ALERT_LOG_FILE;
 if [ $TELEGRAM_TYPE != "papampi" -o $TELEGRAM_ALERTS == "NO" ];
 then 
  echo -e "${B}${Y}$(date)${N} - ${C}Starting autotemp script.${N}"|tee -a ${LOG_FILE};
 fi;
 if [[ $TELEGRAM_TYPE == "papampi"&&$TELEGRAM_ALERTS == "YES" ]];
 then 
  echo -e "${B}${Y}$(date)${N} - ${C}Starting autotemp script.${N}"|tee -a ${LOG_FILE};
 fi;
};

MAKE_WTM_LOGS(){ 
 source ~/1bash;
 source ~/8Coins;
 source ~/1oc;
 touch /home/m1/Logs/WTM_current_revenue;
 LOG3_FILE="/home/m1/Logs/8_wtmautoswitchlog";
 if [[ -e "$LOG_FILE" ]];
 then 
  echo "$(cat $LOG3_FILE|tail -n 5k)">$LOG3_FILE;
 fi;
 WTM_HISTORY="/home/m1/Alerts/WTM_switch_history";
 if [[ -e "$WTM_HISTORY" ]];
 then 
  echo "$(cat $WTM_HISTORY|tail -n 100)">$WTM_HISTORY;
 fi;
 FIRST_COIN="$(echo $WTM_AUTO_SWITCH_COINS|awk -F'[_;]' '{print $1}')";
 TOP_COIN=$(cat /home/m1/Logs/WTM_top_coin|sed 's/:[0-9]*//');
 if [ -z $(echo $WTM_AUTO_SWITCH_COINS|grep $TOP_COIN)];
 then 
  echo "Last top coin not in current coin list any more, Switch to 1st coin";
  touch $TOP_COIN;
  sed -i "s/$COIN/ZZ/g" /home/m1/Logs/WTM_top_coin;
 fi;
};

Make_LOGS(){ 
 TAIL_GPU_COUNT=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits|tail -1|awk '{ SUM += $1+3} ;{ print SUM }');
 echo -e "${B}${Y}Displaying the last known lines of the miner log -USE THIS TO TROUBLESHOOT-${N}";
 MINER_LOG=$(tail -n $TAIL_GPU_COUNT /home/m1/Logs/screenlog.0|sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'|awk '{print $0,""}');
 echo $MINER_LOG;
 echo "";
 LOG1_FILE="/home/m1/Logs/5_wdog_log";echo -e "${B}${Y}Displaying the last 20 lines of Restart Logs${N}";
 tail -20 $LOG1_FILE;
 echo "";
 echo -e "${B}${Y}Displaying the last 20 lines of WatchDog Alert Logs${N}";
 ALERT1_LOG_FILE="/home/m1/Alerts/7_wdog_alertlog";
 tail -20 $ALERT1_LOG_FILE;
 echo "";
 echo "";
 LOG_FILE="/home/m1/Logs/6_autotemplog";
 echo -e "${B}${Y}Displaying the last 20 lines of Temp Logs${N}";
 tail -20 $LOG_FILE;
 OC_FILE="/home/m1/Logs/6_autooclog";
 echo "";
 echo -e "${B}${Y}Displaying the last known Overclock Settings${N}";
 GPU_COUNT=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits|tail -1);
 OCSETTINGS=$(tail -n 50 /home/m1/Logs/6_autooclog|grep GPU|awk '{gsub(/:/,": ")}1'|tail -n $GPU_COUNT|sed -r ''|awk '{print $0,""}');
 echo $OCSETTINGS;
 echo "";
 echo -e "${B}${Y}Displaying the last 20 lines of Auto Temp Alert Logs${N}";
 ALERT_LOG_FILE="/home/m1/Alerts/6_temp_alertlog";
 tail -20 $ALERT_LOG_FILE;
};


Clear_Logs1(){
 cd /home/m1;
 >/home/m1/Logs/5_wdog_log;
 >/home/m1/Logs/6_autotemplog;
 >/home/m1/Logs/6_autooclog;
 >/home/m1/Alerts/6_autooclastlog;
 >/home/m1/Logs/current-profit;
 >/home/m1/Logs/algo-log;
 >/home/m1/Alerts/7_wdog_alertlog;
 >/home/m1/Alerts/6_temp_alertlog;
 >/home/m1/Logs/8_wtmautoswitchlog;
 >/home/m1/Logs/top_coin;
 >/home/m1/Alerts/WTM_switch_history;
 >/home/m1/Logs/WTM_current_profit;
 >/home/m1/Alerts/WTM_24H_REV;
 >/home/m1/Logs/WTM_current_revenue;
 >/home/m1/Logs/screenlog.0;
 echo "Cleared.";
};