#!/bin/bash
tel_TELEGRAM(){
# source ~/1bash
# source ~/Resources

 CHATID=$TELEGRAM_CHATID
 APIKEY=$TELEGRAM_APIKEY

 SYSTEM_BOOT_TIME=$(uptime -s)
 SYSTEM_UP_TIME=$(uptime -p)
 GPU_COUNT=$(nvidia-smi -i 0 --query-gpu=count --format=csv,noheader,nounits)
 let GPU_COUNT1=$GPU_COUNT+1
 REBOOT_REQUIRED=$([ -f /var/run/reboot-required ] && echo "Yes!!!" || echo "No")
 GPU_UTILIZATIONS=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits | tr '\n' '   ')
 TEMP_FAN_POWER=$(tail  -n 50 /home/m1/Logs/6_autotemplog  | grep GPU | awk '{gsub(/:/,": ")}1' |tail -n $GPU_COUNT | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g')
 WDOG_WARNINGS=$(tail  -n 50 /home/m1/Alerts/7_wdog_alertlog | grep WARNING | awk '{gsub(/:/,": ")}1' |tail -n $GPU_COUNT | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'  | awk '{print $0}' )
 TEMP_WARNINGS=$(tail  -n 50 /home/m1/Alerts/6_temp_alertlog | grep WARNING | awk '{gsub(/:/,": ")}1' |tail -n $GPU_COUNT | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'  | awk '{print $0}' )


 if [[ -n  $(ps ax | grep SCREEN | grep miner | awk '"miner" {print $1}') ]]
 then
  MINER_PID=$(ps ax | grep SCREEN | grep miner | awk '"miner" {print $1}')
  MINER_UP_TIME=$(ps -p $MINER_PID -o etime | grep -v ELAPSED)
 else
  MINER_UP_TIME=("Not Running")
 fi

 LF=$'\n'
 MSG=$(echo "Telegram Name: $TELEGRAM_NAME $LF $LF Worker: $WORKERNAME $LF Boot Time: $SYSTEM_BOOT_TIME $LF System Up Time: $SYSTEM_UP_TIME $LF Miner Uptime: $MINER_UP_TIME $LF Currently Mining: $CURRENT_COIN $LF BTC Price: $BTC_PRICE_VALUE $LF Reboot Required: $REBOOT_REQUIRED $LF GPU Count: $GPU_COUNT $LF GPU Utilization: $LF $GPU_UTILIZATIONS $LF Temp, Fan, Power: $LF $TEMP_FAN_POWER $LF $LF Auto Switch: $LF$AUTO_SWITCH $LF $LF Watchdog Alerts: $LF $WDOG_WARNINGS $LF $LF Temp Alerts: $LF $TEMP_WARNINGS $LF $LF CURRENT HASH: $LF $CURRENTHASH")
 /usr/bin/curl -m 5 -s -X POST --output /dev/null https://api.telegram.org/bot${APIKEY}/sendMessage -d "text=${MSG}" -d chat_id=${CHATID}
}

TELEGRAM_TYPE="papampi";

TELESR(){
 WDOG_WARNINGS=$(tail -n 50 /home/m1/Alerts/7_wdog_alertlog|grep WARNING|awk '{gsub(/:/,": ")}1'|tail -n $GPU_COUNT|sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'|awk '{print $0}');
 TELEGRAM_SYSTEMRESTARTS="NO";
 source ~/1bash;
 if [ $TELEGRAM_SYSTEMRESTARTS == "YES" ];
 then 
  CHATID=$TELEGRAM_CHATID;
  APIKEY=$TELEGRAM_APIKEY;
  GPU_COUNT=$(nvidia-smi -i 0 --query-gpu=count --format=csv,noheader,nounits);
  WDOG_WARNINGS=$(tail -n $GPU_COUNT /home/m1/Alerts/7_wdog_alertlog|grep WARNING|awk '{gsub(/:/,": ")}1'|sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'|awk '{print $0}');
  LF=$'\n';
  MSG=$(echo "Telegram Name: $TELEGRAM_NAME $LF $LF Worker: $WORKERNAME $LF $LF WATCHDOG RESTARTED SYSTEM. $LF $LF Watchdog Alerts: $LF $WDOG_WARNINGS");
  /usr/bin/curl -m 5 -s -X POST --output /dev/null https://api.telegram.org/bot${APIKEY}/sendMessage -d "text=${MSG}" -d chat_id=${CHATID};
 fi;
};

TELEMR(){ 
 WDOG_WARNINGS=$(tail -n 50 /home/m1/Alerts/7_wdog_alertlog|grep WARNING|awk '{gsub(/:/,": ")}1'|tail -n $GPU_COUNT|sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'|awk '{print $0}');
 TELEGRAM_MINERRESTARTS="NO";
 source ~/1bash;
 if [ $TELEGRAM_MINERRESTARTS == "YES" ];
 then 
  CHATID=$TELEGRAM_CHATID;
  APIKEY=$TELEGRAM_APIKEY;
  GPU_COUNT=$(nvidia-smi -i 0 --query-gpu=count --format=csv,noheader,nounits);
  WDOG_WARNINGS=$(tail -n $GPU_COUNT /home/m1/Alerts/7_wdog_alertlog|grep WARNING|awk '{gsub(/:/,": ")}1'|sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'|awk '{print $0}');
  LF=$'\n';
  MSG=$(echo "Telegram Name: $TELEGRAM_NAME $LF $LF Worker: $WORKERNAME $LF $LF WATCHDOG RESTARTED MINER. $LF $LF Watchdog Alerts: $LF $WDOG_WARNINGS");
  /usr/bin/curl -m 5 -s -X POST --output /dev/null https://api.telegram.org/bot${APIKEY}/sendMessage -d "text=${MSG}" -d chat_id=${CHATID};
 fi;
};

TELEMS(){ 
 WDOG_WARNINGS=$(tail -n 50 /home/m1/Alerts/7_wdog_alertlog|grep WARNING|awk '{gsub(/:/,": ")}1'|tail -n $GPU_COUNT|sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'|awk '{print $0}');
 TELEGRAM_SYSTEMRESTARTS="NO";
 source ~/1bash;
 if [ $TELEGRAM_SYSTEMRESTARTS == "YES" ];
 then 
  CHATID=$TELEGRAM_CHATID;
  APIKEY=$TELEGRAM_APIKEY;
  LF=$'\n';
  MSG=$(echo "Telegram Name: $TELEGRAM_NAME $LF $LF Worker: $WORKERNAME $LF $LF SYSTEM IS STARTING $LF $LF Watchdog Alerts: $LF $WDOG_WARNINGS");
  /usr/bin/curl -m 5 -s -X POST --output /dev/null https://api.telegram.org/bot${APIKEY}/sendMessage -d "text=${MSG}" -d chat_id=${CHATID};
 fi;
};